Initial Commit
traveloka/terraform-aws-common-iam-roles pull request #1
Opened 2018-04-10 09:51 UTC by ronny-kaluge

2018-04-10 12:51 UTC, andysaputra requested changes

2018-04-10 12:51 UTC, andysaputra commented on examples/datadog-role/main.tf
> +  source = "../../modules/datadog-role" # In actual use case, you have to replace this line with: source = "github.com/traveloka/terraform-aws-common-iam-roles.git?ref=v0.1.0"
seems like the comment is wrong

2018-04-11 04:16 UTC, andysaputra approved these changes
lgtm

2018-04-11 04:17 UTC, merged

2018-04-11 08:58 UTC, arief-halim commented on modules/datadog-role/main.tf
> +  datadog_account_id = "464622532012"
Are we going to use the same datadog account id for all products and all environment (prod & staging)?